
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "context",
    srcs = glob(["**/*.cc"]),
    hdrs = glob(["**/*.h"]),
    include_prefix = "src/context",
    deps = [
      "//api",
      "//sdk:headers",
    ],
)
